version: '2'
services:
    store-app:
        image: store
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://store-postgresql:5432/store
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    store-postgresql:
        extends:
            file: postgresql.yml
            service: store-postgresql
